name: Bootcamp 2020 urdu
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      
    - name: Installing surge
      run: npm install --global surge
    - name: Deploying using surge
      run: surge ./ yasir_123.surge.sh --token $ {{ secrets.SURGE_TOKEN2 }} 
        
